### ISSUE TITLE
Device class for monthly energy monitor is wrong

### ISSUE THREAD

**Issue by pims848** [Refoss/refoss-homeassistant#5]
Hi,

The current energy monitor device class for EM06 device is `total`.
With such class if you use home assistant energy dashboard then on the first of each month when the sensor `*._this_month_energy` counter resets to 0 the delta energy is false. 

Example: your counter was 13.4KWh on the 31st when the counters is back to 0 the energy dashboard will show 0 - 13,4 = -13.4KWh

The result is a negative spike in your energy dashboard.

The correct class entity should be `total_increasing`  

To fix this for now I've overwritten the sensor device class like this: 
```
  customize:
    # Add an entry for each entity that you want to overwrite.
    sensor.em06_a1_this_month_energy:
      state_class: total_increasing
    sensor.em06_a2_this_month_energy:
      state_class: total_increasing
    sensor.em06_b1_this_month_energy:
      state_class: total_increasing
    sensor.em06_b2_this_month_energy:
      state_class: total_increasing
    sensor.em06_c1_this_month_energy:
      state_class: total_increasing
    sensor.em06_c2_this_month_energy:
      state_class: total_increasing
```

It would be cleaner to fix it in sensor.py just by replacing TOTAL by TOTAL_INCREASING.
Thanks.
